spring:
  data:
    mongodb:
      uri: mongodb://admin:123456@localhost:27017/order_service?authSource=admin

jwt:
  signerKey: "3m47O+gM3Sc0lc9I5pMhfGFZMoqvbFtLoNs6Lmq9nOg="

server:
  port: 8081


